### ISSUE TITLE
would you implement xLSTM_PPO?

### ISSUE THREAD

**Issue by ping678** [CAI23sbP/GRU_AC#1]
It would be  very helpful for verifying the effect of xLSTM in same environment.

**Comment by CAI23sbP** [comment]
@ping678 Thank you for your interesting.
To reply your issue, I don't have a plan about xLSTM_PPO 
As you know, my project is just adding GRU network to stable-baselines3 PPO.
If you have to do it, I suggest that you change from LSTM to XLSTM.
