### ISSUE TITLE
Running a personalized environment fails

### ISSUE THREAD

**Issue by dajianer** [CAI23sbP/GRU_AC#2]
When I tested the error in my own designed environment, do you know why?
![image](https://github.com/user-attachments/assets/cfa395bf-f1b5-4377-9c95-b9e42940dc3f)

**Comment by CAI23sbP** [comment]
@dajianer hi, can I see your full code?

**Comment by CAI23sbP** [comment]
@dajianer  
In my opinion, if you want to use a features_extractor , you must input its init values.

Thank you for using my code.
